name: GPT-Memory Nightly

on:
  schedule:
    - cron: "0 19 * * *"   # 22:00 Europe/Sofia
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: gpt-memory-nightly
  cancel-in-progress: false

jobs:
  refresh-top5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pip + jq)
        run: |
          python -m pip install --upgrade pip
          pip install tqdm
          sudo apt-get update && sudo apt-get install -y jq

      - name: Prepare workspace
        run: |
          set -euxo pipefail
          mkdir -p archives out/top5
          echo "Files in archives:"; find archives -type f | head -n 50 || true

      - name: Reindex + Manifest + TOP5
        run: |
          set -euxo pipefail
          python ingest_folder.py archives
          python manifest.py
          bash update_top5.sh

      - name: Upload TOP5 artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: top5-output
          path: |
            out/MANIFEST.*
            out/top5/*.txt

      - name: Commit changes if any
        run: |
          set -e
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -f out/MANIFEST.* out/top5/*.txt
            git commit -m "chore(gpt-memory): nightly refresh $(date -u +'%Y-%m-%dT%H:%MZ')"
            git push
          else
            echo "No changes to commit."
          fi

